name: Run Dockerfile and run apprentice-actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env: 
  IMAGE-TAG: my-image-name:$(date +%s)
    
jobs:
  
  run-image:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag $IMAGE-TAG
        
      - name: Run Docker image
        run: docker run -p 80:80 IMAGE-TAG
        
      - name: run tests
        uses: liatrio/github-actions/apprentice-action@master
